### PR TITLE
encoding + sendtx + utils + query scripts

### PR DESCRIPTION
**Pull request by Juuddi**
Initial pass: c0a1051

Added scripts for the following:
- `query-balance`
- `query-block`
- `send-etx`
- `send-transaction`
- `util-bytes`
- `util-encoding`
- `util-grind-address`
- `util-shard-from-address`

Todo:
- Add scripts for
  - all `contract` examples
  - all `polling` examples
- Add `README.md` docs for all examples

Additional changes
- Install `quais` and `quais-polling` at top level
- Clean up `.gitignore`
- remove bottom level `package.json` files

### CODE REVIEW

**Comment by Juuddi** [comment]
Updates in 38bbdc5
- Build out auto deploy and link script in `deploy-qrc20.js`
- Moved to local `package.json`s as per @alanorwick's request in all example folders
- Added contracts in for QRC20 and QRC721 examples
- Removed `QRC20X` and `QRC721X` as they no longer apply, the standard should always be crosschain. If we want to include non-cross chain token standards for some reason, they should be referred to by their actual EIPs.
- Added QRC20 and QRC721 ABIs for use in the `quais.contractFactory()` and `quais.getContractFactory()` methods
 
Todo:
- Still need to add `README.md`'s for all of the examples, working on finishing code out first and then will write docs
- Port QRC20 autodeploy script to QRC721 

Notes:
- Need to have a conversation about bringing back polling. The lack of polling prevents much of the `provider` and `contract` methods from working properly. They either need to be removed entirely or polling needs to be restored, we can't have a bunch of broken code sitting in a repo with 0 documentation.
- How exactly do we want to poll for logs and events? This can be done via a workaround by polling for a transaction receipt for the time being, but is janky and likely should not be a long term solution.

**Comment by Juuddi** [comment]
Updates in 797ceb7:
- Split out QRC20 and QRC721 folders to include **single** and **multi**chain deploys + interactions
- Add header comments to some scripts for better clarity
- Bump `quais-polling` version in some folders
- Refactor QRC721 contracts to take in constructor args during deployment
- Change `polling-event` and `polling-logs` to `query-event` and `query-logs` respectively as `quais-polling` doesn't provide good coverage, querying will suffice for the time being
- Build out `send-etx` script with gas calculation based on shard differential

TODO: 
- Recompile QRC721 contracts to get new ABIs
- Make updates to [`quais-polling`](https://github.com/dominant-strategies/quais-polling) to accept contract instances alongside providers - will allow polling for contract stuff
- Still need `README.md`'s
- Run through and add comment headers to all scripts

**Comment by Juuddi** [comment]
Updates in [35525ec](https://github.com/dominant-strategies/quais-by-example/pull/1/commits/35525ec06654a8f44412adcbeff1769b0ed5b96c):
- Update overview `README.md`

**Comment by Juuddi** [comment]
Updates in [67b1655](https://github.com/dominant-strategies/quais-by-example/pull/1/commits/67b165531e057f918110f4bac6b44959c21203de):
- Minor variable renames for clarity in deploy scripts
- Add additional clarifying comments for some config objects
- rework language between `ext` and `itx` to better distinguish between internal/external
  - for external: `destination` and `origin`
  - for internal: `to` and `from`
- Pull `rpcURL` out into a variable for each scripts
- `README.md`'s for:
  - `contract-qrc20`
  - `contract-qrc721`
  - `query-balance`
  - `query-block`
  - `query-event`
  - `query-logs`
  - `send-etx`
  - `send-transaction`
  - `util-bytes`
  - `util-encoding`
  - `util-grind-address`
  - `util-shard-from-address`

**Review by 0xalank — CHANGES_REQUESTED** [review]
For the things loading private keys, could you actually do the env file / loading so that other's don't have to create it?

**Comment by Juuddi** [comment]
> For the things loading private keys, could you actually do the env file / loading so that other's don't have to create it?

Fixed in [`ab15d4f`](https://github.com/dominant-strategies/quais-by-example/pull/1/commits/ab15d4f3a3631c6fb88634d43143ebfe2d99ecf9)

**Review by 0xalank — APPROVED** [review]

**Comment by Juuddi** [comment]
Changes in [`ce76962`](https://github.com/dominant-strategies/quais-by-example/pull/1/commits/ce7696255a0122e960552768089c299f28eb675d):
- Update QRC721 abi to match new contract structure (non hardcoded constructor args)

**Pull request merged**
